parameters:
  - name: buildConfiguration
    type: string
  - name: buildPlatform
    type: string
  - name: azureSubscription
    type: string
  - name: fullSolution
    type: string
  - name: functionAppName
    type: string

jobs:
  - job:
    steps:

      - task: UseDotNet@2
        displayName: '.NET 3.1 Core SDK install'
        inputs:
          packageType: 'sdk'
          version: '3.1.x'

      - task: UseDotNet@2
        displayName: '.NET 5 SDK install'
        inputs:
          packageType: 'sdk'
          version: '5.x'

      # NuGet tool installer
      - task: NuGetToolInstaller@1
        displayName: 'NuGet install'
        inputs:
          versionSpec: '5.x'
          checkLatest: true

      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          command: 'restore'
          restoreSolution: ${{parameters.fullSolution}}
          feedsToUse: 'select'
          verbosityRestore: 'Normal'
          includeNuGetOrg: true
          noCache: true

      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          projects:  ${{parameters.fullSolution}}
          arguments: '--configuration ${{parameters.buildConfiguration}}'
          zipAfterPublish: true

      - task: VSTest@2
        displayName: Unit Tests Run
        inputs:
          platform: ${{parameters.buildPlatform}}
          configuration: ${{parameters.buildConfiguration}}

      - task: DotNetCoreCLI@2
        displayName: dotnet publish function --configuration ${{parameters.buildConfiguration}}
        name: PublishFunction
        inputs:
          command: publish
          projects: ${{parameters.fullSolution}}
          publishWebProjects: false
          arguments: '--configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)/function'
          zipAfterPublish: true
      
      - task: AzureFunctionApp@1
        displayName: Azure Function App Deploy
        inputs:
          azureSubscription: ${{parameters.azureSubscription}}
          appType: 'functionApp'
          appName: ${{parameters.functionAppName}}
          package: $(System.ArtifactsDirectory)/function/app.zip
